# Generated by Django 3.2.9 on 2021-12-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20211216_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='file_path',
            field=models.URLField(blank=True, null=True),
        ),
    ]
