# Generated by Django 3.2.9 on 2021-12-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productimage_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='file_path',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
